### ISSUE TITLE
img_time list is empty

### ISSUE THREAD

**Issue by Derekglk** [szad670401/oinbagCrawler#1]
Hi, when I ran the code, there's an error says:

> root        : CRITICAL This is the 1 time to start:2017-08-03 11:30:29
> Traceback (most recent call last):
>   File "collector.py", line 93, in <module>
>     res = main(time_flag)
>   File "collector.py", line 52, in main
>     starttime = img_time[0]
> IndexError: list index out of range

It turns out that the `img_time ` list is empty.
I'm not familiar with HTML and curl, could you please help me with it please?
Thank you very much.

FYI, I printed the result when `source = curl('http://www.oinbag.com')`

```
>>> source = curl('http://www.oinbag.com/')
>>> type(source)
<type 'str'>
>>> print source
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.12.1</center>
</body>
</html>
```

**Comment by szad670401** [comment]
I tried the crawler successfully in last week. the website maybe add the anti-crawler mechanism. 
to approach this issue.please add "--user-agent" parameter.
Line 12
    cmd = ['curl', '--connect-timeout', '8', '-m', '8', url]
->
    cmd = ['curl', '--connect-timeout', '8', '-m', '8', url,"--user-agent","Mozilla"]
