### ISSUE TITLE
请问运行出现这样的错误是什么原因

### ISSUE THREAD

**Issue by exfocus** [szad670401/oinbagCrawler#2]
python3 collector.py 
root        : CRITICAL This is the 1 time to start:2017-08-15 15:39:20
Traceback (most recent call last):
  File "collector.py", line 80, in <module>
    res = main(time_flag)
  File "collector.py", line 37, in main
    source = curl('http://www.oinbag.com/')
  File "collector.py", line 9, in curl
    getit = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'curl'

**Comment by joker-man** [comment]
if you run it in windows. you must install curl and add to environment variable

**Comment by joker-man** [comment]
if you run it in windows. you must install curl and add to environment variable
