### ISSUE TITLE
请问这个错误该如何解决呢

### ISSUE THREAD

**Issue by Suzhanxue** [szad670401/oinbagCrawler#3]
root        : CRITICAL This is the 1 time to start:2018-03-06 10:28:23
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/oinbagCrawler-master/collector.py", line 93, in <module>
    res = main(time_flag)
  File "C:/Users/Administrator/Desktop/oinbagCrawler-master/collector.py", line 50, in main
    html = etree.HTML(source)
  File "src\lxml\lxml.etree.pyx", line 3176, in lxml.etree.HTML (src\lxml\lxml.etree.c:79033)
  File "src\lxml\parser.pxi", line 1847, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:119092)
ValueError: can only parse strings

**Comment by szad670401** [comment]
用py2.7
